In [302]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC

In [303]:
dataset = load_breast_cancer()

In [304]:
df = pd.DataFrame(dataset.data, columns = dataset.feature_names)

In [305]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [306]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [307]:
df['result'] = dataset.target

In [308]:
df.result.unique()

array([0, 1])

In [309]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,result
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [310]:
from sklearn.model_selection import train_test_split

In [311]:
X = df.drop('result', axis='columns')
y = df.result

In [312]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

In [313]:
model = SVC()
model.fit(X_train, y_train)

SVC()

In [314]:
print(f" The training accuracy is : {model.score(X_train, y_train)}")
print(f" The testing accuracy is : {model.score(X_test, y_test)}")

 The training accuracy is : 0.9186813186813186
 The testing accuracy is : 0.9298245614035088

# Handling Overfitting

In [315]:
model1 = SVC(kernel = 'linear')
model1.fit(X_train, y_train)

SVC(kernel='linear')

In [316]:
print(f" The training accuracy is : {model1.score(X_train, y_train)}")
print(f" The testing accuracy is : {model1.score(X_test, y_test)}")

 The training accuracy is : 0.9582417582417583
 The testing accuracy is : 0.956140350877193

In [317]:
model2 = SVC(C = 10,kernel = 'linear')
model2.fit(X_train, y_train)

SVC(C=10, kernel='linear')

In [318]:
print(f" The training accuracy is : {model2.score(X_train, y_train)}")
print(f" The testing accuracy is : {model2.score(X_test, y_test)}")

 The training accuracy is : 0.9714285714285714
 The testing accuracy is : 0.9649122807017544

In [319]:
model3 = SVC(C = 0.1,kernel = 'linear')
model3.fit(X_train, y_train)

SVC(C=0.1, kernel='linear')

In [320]:
print(f" The training accuracy is : {model2.score(X_train, y_train)}")
print(f" The testing accuracy is : {model2.score(X_test, y_test)}")

 The training accuracy is : 0.9714285714285714
 The testing accuracy is : 0.9649122807017544

### Observations

#### After training and testing, the model performs well when the Kernel is set to "Linear" irrespective of the regularization(C) value

# Random Forest

In [321]:
from sklearn.ensemble import RandomForestClassifier

In [322]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [323]:
print(f" The training accuracy is : {rf.score(X_train, y_train)}")
print(f" The testing accuracy is : {rf.score(X_test, y_test)}")

 The training accuracy is : 1.0
 The testing accuracy is : 0.956140350877193

In [324]:
rf1 = RandomForestClassifier(n_estimators = 200)
rf1.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200)

In [325]:
print(f" The training accuracy is : {rf1.score(X_train, y_train)}")
print(f" The testing accuracy is : {rf1.score(X_test, y_test)}")

 The training accuracy is : 1.0
 The testing accuracy is : 0.9473684210526315

In [326]:
rf2 = RandomForestClassifier(n_estimators = 40)
rf2.fit(X_train, y_train)

RandomForestClassifier(n_estimators=40)

In [327]:
print(f" The training accuracy is : {rf2.score(X_train, y_train)}")
print(f" The testing accuracy is : {rf2.score(X_test, y_test)}")

 The training accuracy is : 1.0
 The testing accuracy is : 0.956140350877193

## Cross Validation

### SVM

In [328]:
from sklearn.model_selection import cross_val_score

In [329]:
cross_val_score(SVC(), X, y, cv=3)

array([0.85263158, 0.93157895, 0.94708995])

In [330]:
cross_val_score(SVC(C = 10, kernel = 'linear'), X, y, cv=3)

array([0.95263158, 0.95789474, 0.95238095])

### Random Forest

In [331]:
cross_val_score(RandomForestClassifier(), X, y, cv=3)

array([0.94736842, 0.96315789, 0.96296296])

In [332]:
cross_val_score(RandomForestClassifier(n_estimators = 40), X, y, cv=3)

array([0.93684211, 0.95789474, 0.96296296])